[package]
name = "chatimpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chatgpt_rs = { version = "1.1.0", features = ["json", "streams"] }
rustpython-parser = "0.2.0"
